/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       StandardCalculator calc = new StandardCalculator();
       calc.add(4, 1);
       calc.printResult();

       ScientificCalculator sCalc = new ScientificCalculator();
       sCalc.cos(10);
       sCalc.printResult();

       LogicCalculator lCalc = new LogicCalculator();
       lCalc.AND(7, 2);
       lCalc.printResult();
    }
}
